# Generated by Django 5.2.8 on 2025-11-23 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('closable', models.BooleanField(default=True, verbose_name='是否可关闭')),
                ('meta_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='菜单meta_id')),
                ('icon', models.CharField(blank=True, max_length=64, null=True, verbose_name='菜单图标')),
                ('path', models.CharField(max_length=128, verbose_name='前端路由路径')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('describe', models.CharField(blank=True, max_length=300, null=True, verbose_name='菜单描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menu', verbose_name='父菜单')),
            ],
        ),
    ]
