"""
Django settings for RestFramework project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import sys
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# 把apps文件夹加入到项目根的搜索路径，导入的时候，可以直接从源码包中导入
sys.path.insert(0, str(BASE_DIR))
sys.path.insert(0, os.path.join(BASE_DIR, "apps"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p$+vmfayhkak%lcm0r-^eart&(+)3wqqsd_*x5l(4gnh_g2w*!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['10.0.9.21', '10.0.2.179', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_filters',
    'rest_framework',
    'rest_framework_simplejwt',
    'apps.user.apps.UserConfig',
    'apps.news.apps.NewsConfig',   
    'apps.menu.apps.MenuConfig',
    'apps.salary.apps.SalaryConfig',
    'django_cas_ng',
]
# 允许所有域名跨域
CORS_ORIGIN_ALLOW_ALL = True
# 允许携带cookie
CORS_ALLOW_CREDENTIALS = True
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_cas_ng.middleware.CASMiddleware',
]

# CAS服务器URL和版本
CAS_SERVER_URL = 'https://authserver.tyu.edu.cn/authserver/'
# CAS 回调后前端页面
LOGIN_REDIRECT_URL = "http://10.0.2.179/loginSuccess"
CAS_VERSION = '3'
# 存入所有 CAS 服务端返回的 User 数据。
CAS_APPLY_ATTRIBUTES_TO_USER = False
# 关闭默认的重定向（前后端分离不需要）
CAS_REDIRECT_URL = None
# 开启CAS登录后自动创建Django用户（如果用户不存在）
CAS_CREATE_USER = True
# 从CAS返回的属性映射到Django用户字段（按需配置）
CAS_LOCAL_NAME_FIELD = 'employeeId'
# CAS_USER_ATTRIBUTES = {
#     'employeeId': 'username',
#
# }
ROOT_URLCONF = 'RestFramework.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'RestFramework.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'salary',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
# 配置静态文件所在路径,访问路径是 http://127.0.0.1:8000/static/product_images/01.png
STATICFILES_DIRS=[
    os.path.join(BASE_DIR, 'static')
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static_collect')


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_DIRS = (
    os.path.join(BASE_DIR, 'media')
)


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 指定自定义用户模型
AUTH_USER_MODEL = 'user.UserInfo'

# 配置认证后端
AUTHENTICATION_BACKENDS = [
    'apps.user.backends.EmployeeIdBackend',  # 自定义的工号认证后端
    'django.contrib.auth.backends.ModelBackend',  # Django 默认的用户名认证后端
    'django_cas_ng.backends.CASBackend',  # CAS 认证后端
]

# RestFramework 全局配置
REST_FRAMEWORK = {
    # 添加默认过滤器后端
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

# JWT 配置
SIMPLE_JWT = {
    # access token 有效期（30分钟）
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    # refresh token 有效期（7天）
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    # 是否自动刷新 refresh token（每次刷新时返回新的 refresh token）
    'ROTATE_REFRESH_TOKENS': True,
    # 旧的 refresh token 是否加入黑名单
    'BLACKLIST_AFTER_ROTATION': False,
    # 算法
    'ALGORITHM': 'HS256',
    # 签名密钥（使用 Django 的 SECRET_KEY）
    'SIGNING_KEY': SECRET_KEY,
    # Token 前缀
    'AUTH_HEADER_TYPES': ('Bearer',),
    # Token 在 header 中的名称
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    # User ID 字段
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

