export default [
  {
    path: '/adminHome',
    name: 'adminHome',
    component: () => import('@/views/system/AdminHome.vue'),
    meta: { title: '主控制台', closable: true, requiresAuth: true },
  },
  {
    path: '/bannersAdmin',
    name: 'bannersAdmin',
    component: () => import('@/views/system/news/AdminBanners.vue'),
    meta: { title: '轮播图管理', closable: true, requiresAuth: true },
  },
  {
    path: '/categoryGroupAdmin',
    name: 'categoryGroupAdmin',
    component: () => import('@/views/system/news/CategoryGroupAdmin.vue'),
    meta: { title: '栏目组管理', closable: true, requiresAuth: true },
  },
  {
    path: '/categoryAdmin',
    name: 'categoryAdmin',
    component: () => import('@/views/system/news/CategoryAdmin.vue'),
    meta: { title: '分类管理', closable: true, requiresAuth: true },
  },
  {
    path: '/articlesAdmin',
    name: 'articlesAdmin',
    component: () => import('@/views/system/news/ArticlesAdmin.vue'),
    meta: { title: '文章管理', closable: true, requiresAuth: true },
  },
  {
    path: '/changePassword',
    name: 'changePassword',
    component: () => import('@/views/system/ChangePassword.vue'),
    meta: { title: '修改密码', closable: true, requiresAuth: true },
  },
  {
    path: '/userAdmin',
    name: 'userAdmin',
    component: () => import('@/views/system/UserAdmin.vue'),
    meta: { title: '用户管理', closable: true, requiresAuth: true },
  },
  {
    path: '/menuAdmin',
    name: 'menuAdmin',
    component: () => import('@/views/system/menu/MenuAdmin.vue'),
    meta: { title: '菜单管理', closable: true, requiresAuth: true },
  },
  {
    path: '/roleAdmin',
    name: 'roleAdmin',
    component: () => import('@/views/system/menu/RoleAdmin.vue'),
    meta: { title: '角色管理', closable: true, requiresAuth: true },
  },
  {
    path: '/yearAndMonthAdmin',
    name: 'yearAndMonthAdmin',
    component: () => import('@/views/system/salary/YearAndMonthAdmin.vue'),
    meta: { title: '年月管理', closable: true, requiresAuth: true },
  },
  {
    path: '/salaryYingFaAdmin',
    name: 'salaryYingFaAdmin',
    component: () => import('@/views/system/salary/SalaryYingFaAdmin.vue'),
    meta: { title: '应发工资管理', closable: true, requiresAuth: true },
  },
  {
    path: '/salaryKouKuanAdmin',
    name: 'salaryKouKuanAdmin',
    component: () => import('@/views/system/salary/SalaryKouKuanAdmin.vue'),
    meta: { title: '扣款管理', closable: true, requiresAuth: true },
  },
  {
    path: '/departmentAdmin',
    name: 'departmentAdmin',
    component: () => import('@/views/system/user/DepartmentAdmin.vue'),
    meta: { title: '部门管理', closable: true, requiresAuth: true },
  },
  {
    path: '/titleCategoryAdmin',
    name: 'titleCategoryAdmin',
    component: () => import('@/views/system/user/TitleCategoryAdmin.vue'),
    meta: { title: '职称分类管理', closable: true, requiresAuth: true },
  },
  {
    path: '/employeeProfileAdmin',
    name: 'employeeProfileAdmin',
    component: () => import('@/views/system/user/EmployeeProfileAdmin.vue'),
    meta: { title: '员工档案管理', closable: true, requiresAuth: true },
  },
  {
    path: '/employeeTitleHistoryAdmin',
    name: 'employeeTitleHistoryAdmin',
    component: () => import('@/views/system/user/EmployeeTitleHistoryAdmin.vue'),
    meta: { title: '员工职称历史管理', closable: true, requiresAuth: true },
  },
  {
    path: '/operationLogAdmin',
    name: 'operationLogAdmin',
    component: () => import('@/views/system/user/OperationLogAdmin.vue'),
    meta: { title: '操作日志管理', closable: true, requiresAuth: true },
  },
]