# Generated by Django 5.2.8 on 2026-01-17 01:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YearAndMonth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='年份')),
                ('month', models.IntegerField(verbose_name='月份')),
            ],
            options={
                'db_table': 'YearAndMonth',
                'ordering': ['-id'],
            },
        ),
    ]
