# Generated by Django 5.2.8 on 2026-01-17 02:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryKouKuan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('daikouzhufanggongjijin', models.FloatField(default=0, verbose_name='代扣住房公积金')),
                ('yiliaobaoxian', models.FloatField(default=0, verbose_name='医疗保险')),
                ('bujiaoyiliaobaoxian', models.FloatField(default=0, verbose_name='补缴医疗保险')),
                ('yanglaobaoxian', models.FloatField(default=0, verbose_name='养老保险')),
                ('bujiaoyanglao', models.FloatField(default=0, verbose_name='补缴养老')),
                ('zhiyenianjin', models.FloatField(default=0, verbose_name='职业年金')),
                ('bujiaonianjin', models.FloatField(default=0, verbose_name='补缴年金')),
                ('shiyebaoxian', models.FloatField(default=0, verbose_name='失业保险')),
                ('bujiaoshiye', models.FloatField(default=0, verbose_name='补缴失业')),
                ('gerensuodeshui', models.FloatField(default=0, verbose_name='个人所得税')),
            ],
            options={
                'db_table': 'SalaryKouKu',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryYingFa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baoliujintie', models.FloatField(default=0, verbose_name='保留津贴')),
                ('zhufangbutie', models.FloatField(default=0, verbose_name='住房补贴')),
                ('zhufanggongjijin', models.FloatField(default=0, verbose_name='住房公积金')),
                ('dushengfei', models.FloatField(default=0, verbose_name='独生费')),
                ('weishengfei', models.FloatField(default=0, verbose_name='卫生费')),
                ('gangweigongzi', models.FloatField(default=0, verbose_name='岗位工资')),
                ('jiaohulingjintie', models.FloatField(default=0, verbose_name='教护龄津贴')),
                ('xinjigongzi', models.FloatField(default=0, verbose_name='薪级工资')),
                ('jichujixiaojiang', models.FloatField(default=0, verbose_name='基础绩效奖')),
                ('jichuxingjixiaogongzi', models.FloatField(default=0, verbose_name='基础性绩效工资')),
                ('dongjiqunuanfei', models.FloatField(default=0, verbose_name='冬季取暖费')),
                ('qitabufagongzi', models.FloatField(default=0, verbose_name='其他补发工资')),
                ('linshigongzi', models.FloatField(default=0, verbose_name='临时工资')),
                ('nianzhongjikaoheyouxiujiang', models.FloatField(default=0, verbose_name='年终及考核优秀奖')),
                ('daikouzhufanggongjijin', models.FloatField(default=0, verbose_name='代扣住房公积金')),
                ('bufagongzi', models.FloatField(default=0, verbose_name='补发工资')),
                ('bufadushengfei', models.FloatField(default=0, verbose_name='补发独生费')),
                ('danweimingcheng', models.CharField(blank=True, max_length=100, null=True, verbose_name='单位名称')),
                ('renyuanzhuangkuang', models.CharField(max_length=100, verbose_name='人员状况')),
                ('daifayinhang', models.CharField(blank=True, max_length=100, null=True, verbose_name='代发银行')),
                ('yingfagongzi', models.FloatField(default=0, verbose_name='应发工资')),
                ('danweidaima', models.CharField(blank=True, max_length=100, null=True, verbose_name='单位代码')),
                ('zhixingshijian', models.DateField(blank=True, null=True, verbose_name='执行时间')),
                ('shifagongzhi', models.FloatField(default=0, verbose_name='实发工资')),
            ],
            options={
                'db_table': 'SalaryYingFa',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='yearandmonth',
            name='beizhu',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
