# Generated by Django 5.2.8 on 2026-01-17 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_salarykoukuan_salaryyingfa_yearandmonth_beizhu'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salarykoukuan',
            table='SalaryKouKuan',
        ),
    ]
