# Generated by Django 5.2.8 on 2026-01-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_alter_salarykoukuan_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarykoukuan',
            name='shenfenzhenghao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='salarykoukuan',
            name='xingming',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='salaryyingfa',
            name='shenfenzhenghao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='salaryyingfa',
            name='xingming',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名'),
        ),
    ]
