# Generated by Django 5.2.8 on 2026-01-17 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_salarykoukuan_shenfenzhenghao_salarykoukuan_xingming_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarykoukuan',
            name='year_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.yearandmonth', verbose_name='年月'),
        ),
        migrations.AddField(
            model_name='salaryyingfa',
            name='year_month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salary.yearandmonth', verbose_name='年月'),
        ),
        migrations.AddField(
            model_name='yearandmonth',
            name='year_month',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='年月'),
        ),
    ]
