# Generated by Django 5.2.8 on 2026-01-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0005_salarykoukuan_year_month_salaryyingfa_year_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarykoukuan',
            name='heji',
            field=models.FloatField(default=0, verbose_name='合计'),
        ),
    ]
