# Generated by Django 5.2.8 on 2026-01-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_salarykoukuan_heji'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='salarykoukuan',
            table='salarykoukuan',
        ),
        migrations.AlterModelTable(
            name='salaryyingfa',
            table='salaryyingfa',
        ),
        migrations.AlterModelTable(
            name='yearandmonth',
            table='yearandmonth',
        ),
    ]
