# Generated by Django 5.2.8 on 2025-11-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('order', models.IntegerField(blank=True, default=1, null=True)),
                ('pic', models.CharField(blank=True, max_length=500, null=True)),
                ('is_show', models.BooleanField(blank=True, default=True, null=True)),
                ('link_url', models.CharField(blank=True, max_length=300, null=True)),
                ('desc', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'Banner',
                'ordering': ['-order'],
            },
        ),
    ]
