# Generated by Django 5.2.8 on 2025-11-13 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='news.category')),
            ],
            options={
                'db_table': 'Category',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pic', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('out_link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_check', models.BooleanField(default=True)),
                ('is_top', models.BooleanField(default=False)),
                ('is_hot', models.BooleanField(default=False)),
                ('hits', models.IntegerField(default=0)),
                ('is_delete', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category')),
            ],
            options={
                'db_table': 'Article',
                'ordering': ['is_check', '-is_top', '-create_date'],
            },
        ),
    ]
