# Generated by Django 5.2.8 on 2026-01-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_categorygroup_category_group'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
        migrations.AlterModelTable(
            name='banner',
            table='banner',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='categorygroup',
            table='categorygroup',
        ),
    ]
