# Generated by Django 5.2.8 on 2025-11-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='角色名称')),
                ('describe', models.CharField(blank=True, max_length=300, null=True, verbose_name='角色描述')),
                ('menus', models.ManyToManyField(blank=True, related_name='roles', to='menu.menu', verbose_name='菜单')),
            ],
            options={
                'db_table': 'Role',
                'ordering': ['-id'],
            },
        ),
    ]
