# Generated by Django 5.2.8 on 2026-01-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_role_extra_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='employeeId',
            field=models.CharField(max_length=100, null=True, verbose_name='工号'),
        ),
    ]
