# Generated by Django 5.2.8 on 2026-01-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userinfo_employeeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='idCard',
            field=models.CharField(max_length=18, null=True, verbose_name='身份证号'),
        ),
    ]
