# Generated by Django 5.2.8 on 2026-02-07 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='user.titlecategory', verbose_name='上级分类')),
            ],
            options={
                'verbose_name': '职称分类',
                'verbose_name_plural': '职称分类',
                'db_table': 'title_category',
                'ordering': ['order', 'id'],
            },
        ),
    ]
