# Generated by Django 5.2.8 on 2026-02-07 14:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_titlecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employeeId', models.CharField(max_length=100, unique=True, verbose_name='工号')),
                ('realName', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('idCard', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], max_length=10, null=True, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('telephone', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系电话')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=300, null=True, verbose_name='家庭住址')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='入职日期')),
                ('status', models.CharField(choices=[('active', '在职'), ('leave', '离职'), ('retire', '退休')], default='active', max_length=20, verbose_name='员工状态')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='user.department', verbose_name='所属部门')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '员工档案',
                'verbose_name_plural': '员工档案',
                'db_table': 'employee_profile',
                'ordering': ['-created_at'],
            },
        ),
    ]
