# Generated by Django 5.2.8 on 2026-02-07 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_employeeprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTitleHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('is_current', models.BooleanField(default=False, verbose_name='是否当前职称')),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='证书编号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_history', to='user.employeeprofile', verbose_name='员工')),
                ('title_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_titles', to='user.titlecategory', verbose_name='职称分类')),
            ],
            options={
                'verbose_name': '员工职称历史',
                'verbose_name_plural': '员工职称历史',
                'db_table': 'employee_title_history',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'is_current'], name='employee_ti_employe_cb4619_idx'), models.Index(fields=['start_date', 'end_date'], name='employee_ti_start_d_4e7a0e_idx')],
            },
        ),
    ]
