# Generated by Django 5.2.8 on 2026-02-08 03:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_employeetitlehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=100, verbose_name='操作人姓名')),
                ('action', models.CharField(choices=[('CREATE', '创建'), ('UPDATE', '更新'), ('DELETE', '删除'), ('RETRIEVE', '查询')], max_length=20, verbose_name='操作类型')),
                ('resource_type', models.CharField(max_length=50, verbose_name='资源类型')),
                ('resource_id', models.CharField(max_length=100, verbose_name='资源ID')),
                ('resource_name', models.CharField(max_length=200, verbose_name='资源名称')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['operator', 'created_at'], name='operation_l_operato_b77dbc_idx'), models.Index(fields=['action', 'created_at'], name='operation_l_action_2f1cff_idx'), models.Index(fields=['resource_type', 'created_at'], name='operation_l_resourc_af8aa4_idx')],
            },
        ),
    ]
